### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by linuxissuper** [SebastienDeriaz/home-manager#1]
Hello,  

I was looking how to source the zsh-fzf-tab nix package and found your config and it is working!  
But I don't understand this line `source ${pkgs.zsh-fzf-tab}/share/fzf-tab/fzf-tab.plugin.zsh`  
`pkgs.zsh-fzf-tab` why is this a valid variable?  
Do you have link where I can read about this or can you explain it?

(Sorry if an issue is not the right place for asking this 😅)

**Comment by SebastienDeriaz** [comment]
Hi !
I'm glad my file could help you ! Sadly i didn't wrote it myself, all the credit goes to @ners, maybe he can help you :D

**Comment by ners** [comment]
Thanks for the mention!

@linuxissuper when Nix derivations (as created with `mkDerivation`) are evaluated, they are passed directly to the build scheduler, and their build path in the Nix store is returned. This build path is what is then interpolated into strings.

For example, this is the full path to the binary `ghci` from the package `ghc`: `"${pkgs.ghc}/bin/ghci"`. On my computer, that strings evaluates to:

```
$ nix eval --impure --expr 'let pkgs = import <nixpkgs> {}; in "${pkgs.ghc}/bin/ghci"' 
"/nix/store/kg7g827612mcbjdvxf71spb24z2mx6n7-ghc-9.0.2/bin/ghci"
```

To find out what's contained inside a built derivation's file tree, you can inspect it as any directory, e.g. with `ls`:

```
$ ls $(nix build --no-link --print-out-paths nixpkgs#ghc)
bin  lib  nix-support  share
```

To find out more about Nix internals, I can recommend this excellent article: https://www.tweag.io/blog/2022-07-14-taming-unix-with-nix/

The following web site: https://nix.dev

And the following Youtube video: https://youtu.be/9DJtHIpdp0Y

**Comment by linuxissuper** [comment]
oh, I only thought of bash/shell variables and forgot about nix 🙈   
Thanks for the elaborate answer @ners , I have to do some reading :)

(also thanks @SebastienDeriaz for the help)
